# Generated by Django 6.0.3 on 2026-03-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[("Boys", "Boys"), ("Girls", "Girls"), ("Mixed", "Mixed")],
                        default="Boys",
                        max_length=10,
                    ),
                ),
                ("floors", models.IntegerField(default=1)),
                ("warden_name", models.CharField(blank=True, max_length=100)),
                ("warden_phone", models.CharField(blank=True, max_length=15)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                ("floor", models.IntegerField(default=1)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single Occupancy"),
                            ("Double", "Double Occupancy"),
                            ("Triple", "Triple Occupancy"),
                            ("Dormitory", "Dormitory"),
                        ],
                        default="Double",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=2)),
                (
                    "monthly_rent",
                    models.DecimalField(decimal_places=2, default=3000.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Occupied", "Occupied"),
                            ("Maintenance", "Under Maintenance"),
                            ("Reserved", "Reserved"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("has_ac", models.BooleanField(default=False)),
                ("has_wifi", models.BooleanField(default=True)),
                ("has_attached_bathroom", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.block"
                    ),
                ),
            ],
            options={
                "ordering": ["block", "room_number"],
                "unique_together": {("block", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="RoomAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("allocation_date", models.DateField(auto_now_add=True)),
                ("vacating_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Vacated", "Vacated"),
                            ("Transferred", "Transferred"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.room"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.student"
                    ),
                ),
            ],
            options={
                "ordering": ["-allocation_date"],
            },
        ),
    ]
