# Generated by Django 4.2 on 2026-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0002_roombill"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="roombill",
            index=models.Index(
                fields=["student", "month", "year"],
                name="hostel_room_student_593a0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roombill",
            index=models.Index(fields=["status", "year"], name="hostel_room_status_df4804_idx"),
        ),
        migrations.AddIndex(
            model_name="roombill",
            index=models.Index(fields=["created_at"], name="hostel_room_created_dcac28_idx"),
        ),
        migrations.AddIndex(
            model_name="roombill",
            index=models.Index(fields=["due_date"], name="hostel_room_due_dat_c2d0b1_idx"),
        ),
    ]
