# Generated by Django 6.0.3 on 2026-03-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enrollment_no", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("BTech", "B.Tech"),
                            ("MTech", "M.Tech"),
                            ("MBA", "MBA"),
                            ("MCA", "MCA"),
                            ("BCA", "BCA"),
                            ("BSc", "B.Sc"),
                            ("MSc", "M.Sc"),
                            ("BA", "B.A"),
                            ("MA", "M.A"),
                            ("BPharm", "B.Pharm"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("branch", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("parent_name", models.CharField(max_length=100)),
                ("parent_phone", models.CharField(max_length=15)),
                ("emergency_contact", models.CharField(blank=True, max_length=15)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="students/photos/")),
                ("is_active", models.BooleanField(default=True)),
                ("joining_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
