# Generated by Django 6.0.3 on 2026-03-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Snacks", "Snacks"),
                            ("Dinner", "Dinner"),
                        ],
                        max_length=15,
                    ),
                ),
                ("items", models.TextField()),
                ("timing", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["day", "meal"],
                "unique_together": {("day", "meal")},
            },
        ),
        migrations.CreateModel(
            name="MessRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("Full", "Full Day (B+L+S+D)"),
                            ("Lunch_Dinner", "Lunch + Dinner"),
                            ("Breakfast_Lunch", "Breakfast + Lunch"),
                        ],
                        default="Full",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_charge",
                    models.DecimalField(decimal_places=2, default=3500.0, max_digits=8),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="students.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid"), ("Overdue", "Overdue")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.student"
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
