# Generated by Django 4.2 on 2026-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mess", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="messbill",
            index=models.Index(
                fields=["student", "month", "year"],
                name="mess_messbi_student_f7b8aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messbill",
            index=models.Index(fields=["status", "year"], name="mess_messbi_status_7e97f2_idx"),
        ),
        migrations.AddIndex(
            model_name="messbill",
            index=models.Index(fields=["created_at"], name="mess_messbi_created_012a8a_idx"),
        ),
        migrations.AddIndex(
            model_name="messbill",
            index=models.Index(fields=["due_date"], name="mess_messbi_due_dat_807ce4_idx"),
        ),
        migrations.AddIndex(
            model_name="messbill",
            index=models.Index(fields=["status"], name="mess_messbi_status_f72004_idx"),
        ),
    ]
